import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar, Sidebar } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <header>
            <Navbar />
          </header>
          <div className='flex gap-6 md:gap-20'>
            <div className='h-[92vh] overflow-hidden xl:hover:overflow-auto'>
              <Sidebar />
            </div>
            <main className='mt-4 flex flex-col gap-10 overflow-auto h-[88vh] videos flex-1'>
              {children}
            </main>
          </div>
          <footer>
            Footer
          </footer>
        </div>
      </body>
    </html>
  )
}

export default RootLayout

